---
- name: Total setup for apache
  hosts: server1
  become: yes
  tasks:
    - name: insstalling apache2
      apt:
        name: apache2
        state: present
    - name: copy index file
      copy:
        src: index.html
        dest: /var/www/html
    - name: restart apache2
      service:
        name: apache2
        state: restarted
        enabled: yes
    - name: Firewall
      apt:
        name: firewalld
        state: present
    - name: firewall
      firewalld: 
       permanent: true
       port: "{{item.port}}/{{item.proto}}"
       state: "{{item.state}}"
       zone: "{{item.zone}}"
      with_items:
        - { port: "80", proto: "tcp", state: "enabled", zone: "public"}
    - name: service setup
      service:
        name: firewalld
        state: restarted


